[package]
name = "resonate_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
tokio = { version = "1.44.1", features = ["full"] }
youtube_dl = { version = "0.10.0", features = ["downloader-native-tls"] }
